using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Frameshift
{
    /// <summary>
    /// defines behavior for a Cell, a main class capable of dna translation/transcription etc.
    /// </summary>
    interface ICell
    {
        /// <summary>
        /// Changes the length of the DNA sequence for this cell. Overwrites the current
        /// sequence
        /// </summary>
        /// <param name="len"></param>
        void ChangeSequence(int len);

        /// <summary>
        /// returns the DNA sequence associated with this cell
        /// </summary>
        /// <returns></returns>
        Nucleobase[] GetDNA();

        /// <summary>
        /// returns the RNA sequence associated with this cell
        /// </summary>
        /// <returns></returns>
        Nucleobase[] GetRNA();

        /// <summary>
        /// returns the list of amino acids generated by this cell's dna.
        /// The rules for what AAs are included are determined by the cell's 
        /// ribosome.
        /// </summary>
        /// <returns></returns>
        List<IAminoAcid> GetAminoAcids();

        /// <summary>
        /// Indiscriminately translates the DNA sequence without consulting the 
        /// ribosome for proper translation rules.
        /// </summary>
        List<IAminoAcid> SimpleTranslate();
    }
}