using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Frameshift
{
    /// <summary>
    /// defines behavior for a Cell, a main class capable of dna translation/transcription etc.
    /// </summary>
    interface ICell
    {
        /// <summary>
        /// returns the DNA sequence associated with this cell
        /// </summary>
        /// <returns></returns>
        Nucleobase[] GetDNA();

        /// <summary>
        /// returns the RNA sequence associated with this cell
        /// </summary>
        /// <returns></returns>
        Nucleobase[] GetRNA();

        /// <summary>
        /// returns the list of amino acids generated by this cell's dna
        /// </summary>
        /// <returns></returns>
        List<IAminoAcid> GetAminoAcids();
    }
}